name: Bug Report
description: Report an issue to help us improve
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting your issue please:
        
        - Check if the **Issues section** has a similar issue.
        - Check if the **Wiki section** has an entry about your issue.
  
  - type: input
    id: version
    attributes:
      label: "Version"
      description: "'Latest' is not a valid answer, please write the exact version number."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe your issue.
    validations:
      required: true
  
  - type: input
    id: log-file
    attributes:
      label: Latest Log File
      description: Upload your log file to [https://pastebin.com](https://pastebin.com) and paste a link to it here.
    validations:
      required: false
            
  - type: dropdown
    id: modified-script
    attributes:
      label: "Have you modified the script?"
      description: "Have you changed script, changed variables, or similar?"
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true

  - type: textarea
    id: user-modifications
    attributes:
      label: User Modifications
      description: If you answered "Yes" above, please briefly explain what you have modified.
    validations:
      required: false

  - type: input
    id: discord-username
    attributes:
      label: Discord Username
      description: If you are in the [KuryKat Modding Community](https://discord.gg/7jBSfARh5f) and wouldn't mind being asked further questions there, leave your username here.
      placeholder: username#0000
    validations:
      required: false
